import Head from 'next/head'
import Image from 'next/image'
import Initial from ".//Components/Initial"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className="text-3xl font-bold underline bg-yellow-700">
        <Initial/>
      </body>
    </div>
  )
}
